name: test
on:
  push:
  pull_request:
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure credentials
        uses: tracebit-com/tracebit-community-action@1e35e4fdc6f29832b20ce3e62d85164c32a16a21
        with:
          api-token: ${{ secrets.SECURITY_API_TOKEN }}
          profile: admin
          profile-region: us-east-1
          async: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install -U pip
      - run: pip install -e '.[dev]'
      - run: pytest
      - run: ruff check roguewatch tests
